#!/usr/bin/env -S deno run --allow-read --allow-write
// BotKit by Fedify: A framework for creating ActivityPub bots
// Copyright (C) 2025–2026 Hong Minhee <https://hongminhee.org/>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Asset codegen for BotKit's web pages.
//
// Reads the authoring sources under src/css/ and src/fonts/ and emits two
// committed, runtime-importable modules under src/static/:
//
//  -  style.ts — the design-system stylesheet as a minified string.
//  -  fonts.ts — the bundled web fonts as base64, decoded at load time.
//
// These generated modules ship as source on JSR and are bundled by tsdown for
// npm, so library users get BotKit's front end with no build step of their own.
//
// Run via `mise run generate:assets` whenever the CSS or fonts change, and
// commit the regenerated src/static/*.ts.  This script has no dependencies
// beyond the Deno runtime.

// Canvas mode ships a single quiet, neutral typeface (Inter) so a hosted bot's
// own identity leads.  BotKit's expressive brand type is reserved for BotKit's
// own sites and is not bundled here.
/** Font files to bundle, keyed by the name each is served under. */
const FONTS: readonly string[] = [
  "inter.woff2",
  "inter-italic.woff2",
];

const cssUrl = new URL("../src/css/botkit.css", import.meta.url);
const fontsUrl = new URL("../src/fonts/", import.meta.url);
const staticUrl = new URL("../src/static/", import.meta.url);

const HEADER =
  "// This file is @generated by scripts/build-assets.ts — do not edit.\n" +
  "// deno-fmt-ignore-file\n";

/**
 * Conservatively minifies CSS: strips block comments and collapses runs of
 * whitespace, then trims spaces around structural punctuation.  It deliberately
 * keeps spaces around operators so `calc()` expressions and multi-value
 * properties stay intact, and around `:` so a descendant space before a
 * pseudo-class (e.g. `.bk-prose :is(...)`) is not collapsed into a compound
 * selector.
 *
 * String literals (e.g. `content: "a, b"` or `url("…")`) are stashed before the
 * punctuation pass and restored afterwards, so structural characters inside
 * quotes are never rewritten.  The placeholder is made only of letters, digits,
 * and underscores, so none of the passes below can alter it.
 */
function minifyCss(css: string): string {
  const literals: string[] = [];
  return css
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'/g, (literal) => {
      literals.push(literal);
      return `__BKSTR${literals.length - 1}__`;
    })
    .replace(/\s+/g, " ")
    .replace(/\s*([{};,])\s*/g, "$1")
    .replace(/;}/g, "}")
    .trim()
    .replace(/__BKSTR(\d+)__/g, (_, index) => literals[Number(index)]);
}

/** Encodes bytes as base64 without overflowing the call stack. */
function toBase64(bytes: Uint8Array): string {
  let binary = "";
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
  }
  return btoa(binary);
}

async function buildStyle(): Promise<void> {
  const css = await Deno.readTextFile(cssUrl);
  const minified = minifyCss(css);
  const module = `${HEADER}
/** The BotKit design-system stylesheet, served under a content-hashed path. */
export const css: string = ${JSON.stringify(minified)};
`;
  await Deno.writeTextFile(new URL("style.ts", staticUrl), module);
  console.info(`Wrote src/static/style.ts (${minified.length} bytes of CSS).`);
}

async function buildFonts(): Promise<void> {
  const entries: string[] = [];
  for (const name of FONTS) {
    const bytes = await Deno.readFile(new URL(name, fontsUrl));
    entries.push(
      `  ${JSON.stringify(name)}: ${JSON.stringify(toBase64(bytes))},`,
    );
  }
  const module = `${HEADER}
/** A bundled font file, base64-encoded so it ships as source on JSR. */
export interface FontAsset {
  readonly bytes: Uint8Array;
  readonly mediaType: string;
}

const base64: Record<string, string> = {
${entries.join("\n")}
};

function decode(data: string): Uint8Array {
  const binary = atob(data);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

/** The bundled web fonts, keyed by the file name they are served under. */
export const fonts: Record<string, FontAsset> = Object.fromEntries(
  Object.entries(base64).map(
    ([name, data]) => [name, { bytes: decode(data), mediaType: "font/woff2" }],
  ),
);
`;
  await Deno.writeTextFile(new URL("fonts.ts", staticUrl), module);
  console.info(`Wrote src/static/fonts.ts (${FONTS.length} fonts).`);
}

if (import.meta.main) {
  await Deno.mkdir(staticUrl, { recursive: true });
  await buildStyle();
  await buildFonts();
  console.info("Assets generated.");
}
