// This file is @generated by scripts/build-assets.ts — do not edit.
// deno-fmt-ignore-file

/** The build-time content fingerprint of the stylesheet and fonts. */
export const version: string = "humgf9";
